name: Close Release

on:
  workflow_dispatch:  # Permite execução manual

jobs:
  close_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout release branch
        uses: actions/checkout@v2

      - name: Merge release into main
        run: |
          git checkout main
          git merge --no-ff ${{ github.ref }} || echo "Merge conflicts detected, creating PR"
          git push origin main

      - name: Create Pull Request if merge conflicts occurred
        if: failure()
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Resolve conflicts for release ${{ github.ref }}"
          body: |
            This PR resolves conflicts from the release branch.
          base: main
          head: ${{ github.ref }}

      - name: Merge release into develop
        run: |
          git checkout develop
          git merge --no-ff ${{ github.ref }} || echo "Merge conflicts detected, creating PR"
          git push origin develop

      - name: Create Pull Request if merge conflicts occurred for develop
        if: failure()
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Resolve conflicts for release ${{ github.ref }} (develop)"
          body: |
            This PR resolves conflicts from the release branch into develop.
          base: develop
          head: ${{ github.ref }}

      - name: Criar tag e release no GitHub
        run: |
          VERSION=${{ github.ref_name }}
          git tag -a $VERSION -m "Release $VERSION"
          git push origin $VERSION

      - name: Criar release no GitHub
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: "Release criada via GitHub Actions."
          draft: false
          prerelease: false
